### ISSUE TITLE
tar with extended attributes issue

### ISSUE THREAD

**Issue by p0ll3n** [gvenzl/oci-oracle-xe#249]
Hello. I am experiencing the following issue
```docker pull gvenzl/oracle-xe:21.3.0-slim
21.3.0-slim: Pulling from gvenzl/oracle-xe
ed89681b0b97: Pull complete
2f1b532c6493: Extracting [==================================================>]  61.77MB/61.77MB
7e6108c46508: Download complete
baae83f5d8a9: Download complete
e8a3aa4ffa2e: Download complete
e8f973afebc3: Download complete
failed to register layer: lsetxattr user.overlay.origin /opt: operation not supported
```

here are my docker info
```$ docker info
Client: Docker Engine - Community
 Version:    26.0.2
 Context:    rootless
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.26.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 26.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  rootless
  cgroupns
 Kernel Version: 6.5.0-15-generic
 Operating System: Ubuntu 23.10
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.811GiB
 Name: lima-amd64-2-vm
 ID: 60177198-53b0-4af2-96d9-5335ee6d9da7
 Docker Root Dir: /home/glecocq.linux/.local/share/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

I have the feeling that it could be linked to this known limitation : https://docs.docker.com/engine/release-notes/25.0/#known-limitations

**Comment by p0ll3n** [comment]
it seems that building with recent version of buildah may solve the pb
https://github.com/containers/storage/pull/1847

**Comment by gvenzl** [comment]
Hey @p0ll3n,

Thanks a lot for using these images.

Unfortunately, there is little that I can do here.
These images are built on a Rocky Linux 9 environment and will soon be refreshed.

But given that there is nothing here that is done wrongly in the build of the image itself, but rather when pulling and extracting the image, there is not much else I can do here.

**Comment by SimSonic** [comment]
Our infrustructure updated all docker daemons on GitLab runners to 26.0.x, so we no more can run Testcontainers with `gvenzl/oracle-xe`.

```
Caused by: org.testcontainers.containers.ContainerFetchException: Failed to get Docker client for gvenzl/oracle-xe:21-slim
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:124)
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:33)
	at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
	at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:41)
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1362)
	... 6 common frames omitted
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: failed to register layer: lsetxattr user.overlay.origin /opt: operation not supported
	at com.github.dockerjava.api.command.PullImageResultCallback.checkDockerClientPullSuccessful(PullImageResultCallback.java:97)
	at com.github.dockerjava.api.command.PullImageResultCallback.throwFirstError(PullImageResultCallback.java:112)
	at com.github.dockerjava.api.async.ResultCallbackTemplate.awaitCompletion(ResultCallbackTemplate.java:93)
	at org.testcontainers.images.TimeLimitedLoggedPullImageResultCallback.awaitCompletion(TimeLimitedLoggedPullImageResultCallback.java:58)
	at org.testcontainers.images.RemoteDockerImage.pullImage(RemoteDockerImage.java:163)
	at org.testcontainers.images.RemoteDockerImage.lambda$tryImagePullCommand$1(RemoteDockerImage.java:138)
	at org.testcontainers.shaded.org.awaitility.core.CallableCondition$ConditionEvaluationWrapper.eval(CallableCondition.java:99)
	at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.testcontainers.shaded.org.awaitility.core.SameThreadExecutorService.execute(SameThreadExecutorService.java:79)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:101)
	at org.testcontainers.shaded.org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.testcontainers.shaded.org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:105)
	... 10 common frames omitted
```

**Comment by gvenzl** [comment]
Hi @p0ll3n and @SimSonic,

All images have been refreshed with a build from a newer buildah version (`buildah version 1.35.2 (image-spec 1.1.0, runtime-spec 1.1.0)`) that supposedly should have the fix as outlined in https://github.com/containers/storage/pull/1847

Please let me know whether you still see this issue.

**Comment by SimSonic** [comment]
@gvenzl thanks a lot, now the problems are gone )

**Comment by p0ll3n** [comment]
@gvenzl thanks a lot

**Comment by gvenzl** [comment]
So glad to hear that! Thanks a lot, both!
